INSERT INTO country (co_code, co_name) VALUES ('BS', 'Bahamas');
INSERT INTO country (co_code, co_name) VALUES ('BH', 'Bahrain');
INSERT INTO country (co_code, co_name) VALUES ('BD', 'Bangladesh');
INSERT INTO country (co_code, co_name) VALUES ('BB', 'Barbados');
INSERT INTO country (co_code, co_name) VALUES ('BY', 'Belarus');
INSERT INTO country (co_code, co_name) VALUES ('BE', 'Belgium');
INSERT INTO country (co_code, co_name) VALUES ('BZ', 'Belize');
INSERT INTO country (co_code, co_name) VALUES ('BJ', 'Benin');
INSERT INTO country (co_code, co_name) VALUES ('BM', 'Bermuda');
INSERT INTO country (co_code, co_name) VALUES ('BT', 'Bhutan');
INSERT INTO country (co_code, co_name) VALUES ('BO', 'Bolivia, Plurinational State of');
INSERT INTO country (co_code, co_name) VALUES ('BQ', 'Bonaire, Sint Eustatius and Saba');
INSERT INTO country (co_code, co_name) VALUES ('BA', 'Bosnia and Herzegovina');
INSERT INTO country (co_code, co_name) VALUES ('BW', 'Botswana');
INSERT INTO country (co_code, co_name) VALUES ('BV', 'Bouvet Island');
INSERT INTO country (co_code, co_name) VALUES ('BR', 'Brazil');
INSERT INTO country (co_code, co_name) VALUES ('IO', 'British Indian Ocean Territory');
INSERT INTO country (co_code, co_name) VALUES ('BN', 'Brunei Darussalam');
INSERT INTO country (co_code, co_name) VALUES ('BG', 'Bulgaria');
INSERT INTO country (co_code, co_name) VALUES ('BF', 'Burkina Faso');
INSERT INTO country (co_code, co_name) VALUES ('BI', 'Burundi');
INSERT INTO country (co_code, co_name) VALUES ('KH', 'Cambodia');
INSERT INTO country (co_code, co_name) VALUES ('CM', 'Cameroon');
INSERT INTO country (co_code, co_name) VALUES ('CA', 'Canada');
INSERT INTO country (co_code, co_name) VALUES ('CV', 'Cape Verde');
INSERT INTO country (co_code, co_name) VALUES ('KY', 'Cayman Islands');
INSERT INTO country (co_code, co_name) VALUES ('CF', 'Central African Republic');
INSERT INTO country (co_code, co_name) VALUES ('TD', 'Chad');
INSERT INTO country (co_code, co_name) VALUES ('CL', 'Chile');
INSERT INTO country (co_code, co_name) VALUES ('CN', 'China');
INSERT INTO country (co_code, co_name) VALUES ('CX', 'Christmas Island');
INSERT INTO country (co_code, co_name) VALUES ('CC', 'Cocos (Keeling) Islands');
INSERT INTO country (co_code, co_name) VALUES ('CO', 'Colombia');
INSERT INTO country (co_code, co_name) VALUES ('KM', 'Comoros');
INSERT INTO country (co_code, co_name) VALUES ('CG', 'Congo');
INSERT INTO country (co_code, co_name) VALUES ('IN', 'India');
